spring:
  application:
    name: zuulServer
  ## redis 配置
  redis:
    database: 4
    host: 112.74.43.136
    port: 6379
    password: jingbaobao

server:
  port: 9700

## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:pass@localhost:9000/eureka
    healthcheck:
      enabled: true

zuul:
  ignoredServices: '*' # 忽略所有请求
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    resourceServer: /resourceServer/**
    oauthServer: /oauthServer/**


security:
  oauth2:
    client:
      access-token-uri: http://localhost:8200/oauth/authorize
      client-id: client_2
      client-secret: 123456
      user-authorization-uri: http://localhost:8200/oauth/token
    resource:
      user-info-uri: http://localhost:8200/user
      prefer-token-info: false
      id: order
    sso:
      login-path: http://localhost:8200/login

