spring:
  application:
    name: resourceServer

server:
  port: 8300

## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:pass@localhost:9000/eureka
    healthcheck:
      enabled: true


security:
  oauth2:
#    client:
#      access-token-uri: http://localhost:8200/uaa/oauth/authorize
#      client-id: client_2
#      client-secret: 123456
#      user-authorization-uri: http://localhost:8200/uaa/oauth/token
    resource:
      user-info-uri: http://localhost:8200/user
      prefer-token-info: false
      id: order
    #authorization:
     # check-token-access: http://localhost:8200/oauth/check_token
#    sso:
#      login-path: http://localhost:8400/login
