spring:
  application:
    name: resourceServer

server:
  port: 8300

## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:pass@my.eureka.com:8100/eureka
    healthcheck:
      enabled: true


security:
  oauth2:
    client:
      client-id: client_2
      client-secret: 123456
      access-token-uri: http://my.oauth2.com:8200/oauth/token
    resource:
      token-info-uri: http://my.oauth2.com:8200/oauth/check_token
      user-info-uri: http://my.oauth2.com:8200/oauth/getUserInfo
    authorization:
      check-token-access: http://my.oauth2.com:8200/oauth/check_token
    sso:
      login-path: http://my.oauth2.com:8400/login