spring:
  application:
    name: resourceServer

server:
  port: 8300

## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:pass@localhost:8100/eureka
    healthcheck:
      enabled: true


security:
  oauth2:
    #client:
     # client-id: client_2
      #client-secret: 123456
      #access-token-uri: http://localhost:8200/oauth/token

    resource:
      user-info-uri: http://localhost:8200/getUserInfo
      prefer-token-info: false
    #authorization:
     # check-token-access: http://localhost:8200/oauth/check_token
    sso:
      login-path: http://localhost:8400/login