spring:
  application:
    name: ssoLoginServer
server:
  port: 10000

## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:pass@localhost:9000/eureka
    healthcheck:
      enabled: true


security:
  oauth2:
    client:
      access-token-uri: http://my.cloud.com/oauthServer/oauth/authorize
      client-id: client_2
      client-secret: 123456
      user-authorization-uri: http://my.cloud.com/oauthServer/oauth/token
      authorized-grant-types:
      scope: get_user_info
    resource:
      user-info-uri: http://my.cloud.com/oauthServer/user
      prefer-token-info: false