spring:
  application:
    name: ssoLoginServer
server:
  port: 10000

## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:pass@localhost:9000/eureka
    healthcheck:
      enabled: true


security:
  oauth2:
    client:
      access-token-uri: http://localhost:8200/oauth/token
      client-id: client_2
      client-secret: 123456
      user-authorization-uri: http://localhost:8200/oauth/authorize
      authorized-grant-types: authorization_code
      scope: all
    resource:
      user-info-uri: http://localhost:8200/user
      prefer-token-info: false